language: node_js
node_js:
  - "node"
services:
  - mongodb
cache:
  directories:
    - node_modules
  git:
    - depth: 3
  before_script:
    - cp .env.example .env
  branches:
    only:
      - master
      - develop
  script:
    - npm run test
  addons:
    apt:
      sources:
        - mongodb-upstart
        - sourceline: 'deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
      packages:
        - mongodb-org-server
        - mongodb-org-shell

